// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ7YEgmAd8o_HLHo0XrUjslw8BZEvlCrs',
    appId: '1:431308550425:web:cf03e833064a56daf5d588',
    messagingSenderId: '431308550425',
    projectId: 'dusto-vendor',
    authDomain: 'dusto-vendor.firebaseapp.com',
    storageBucket: 'dusto-vendor.firebasestorage.app',
    measurementId: 'G-NLTF7C66RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkuXZWX3VPRZpxesMtf7feVSYh7ABWMdU',
    appId: '1:431308550425:android:c23960c637f21da7f5d588',
    messagingSenderId: '431308550425',
    projectId: 'dusto-vendor',
    storageBucket: 'dusto-vendor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkz7P4KaRRj7lWBv89N4MJxv7XN_Gv9eI',
    appId: '1:431308550425:ios:e873ba803316e08cf5d588',
    messagingSenderId: '431308550425',
    projectId: 'dusto-vendor',
    storageBucket: 'dusto-vendor.firebasestorage.app',
    iosBundleId: 'com.r3infosolutions.dustovendor',
  );
}
